[tool.poetry]
name = "hw-4"
version = "0.1.0"
description = "tasks"
authors = ["pm <pedromik@mail.ru>"]
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
